### ISSUE TITLE
Gamba can be used to get 0ms time

### ISSUE THREAD

**Issue by WestonReed** [onContentStop/picross#6]
Because the Gamba button randomly picks an unmarked box, if a player simply marked all impossible boxes, they could use the Gamba button to completely fill out the remaining board, and receive the time benefit.

I suggest the time reward for the Gamba button be removed.

**Comment by Phytolizer** [comment]
ee5dd5f8cb9d323ebb7c5728d0f49e46e94dceae fixes this issue by changing the reward of a gamble to be proportional to the chance of losing.
