### ISSUE TITLE
Tabbing out in competitive mode will pause game, and make score unsubmitable

### ISSUE THREAD

**Issue by WestonReed** [onContentStop/picross#7]
When you tab out of the window in competitive mode it will prompt you that if you press pause again, the score will not be submit able, but will do so without user input.

**Comment by Phytolizer** [comment]
Tabbing out performs `doClickAction(bPause)`, which will warn the user but it does not disable competitive mode as far as I am aware.

**Comment by Phytolizer** [comment]
Tabbing out twice in 5 seconds does disable Competitive Mode, so I will disable that functionality.

**Comment by Phytolizer** [comment]
Fixed as of dc81feff86c51f7d7263043c3d24509ab2ee7cad.
